name: flutter_smallworld
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_statusbarcolor: 0.2.0
  video_player: 0.10.1+5
  dio: 2.1.3
  connectivity: 0.4.3+1
  event_bus: 1.1.0
  json_annotation: 2.2.0
  flutter_redux: 0.5.3
  permission_handler: 3.0.1
  photo_manager: 0.3.3
  sqflite: 1.1.5
  path_provider: 1.0.0
  uuid: 2.0.1
  mmkv_flutter: 1.0.10
  package_info: 0.4.0+3
  flutter_bugly: 0.2.0
  flutter_spinkit: 3.1.0
  image_picker: 0.6.0+2
  url_launcher: 5.0.2
  oktoast: 2.1.8
  flare_flutter: 1.5.4
  screen: 0.0.5

dev_dependencies:
  build_runner: 1.1.1
  # flutter packages pub run build_runner build
  json_serializable: 2.2.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - static/flrs/animation_test.flr
    - static/flrs/one_punch.flr
    - static/images/passport/splash_bg.jpg
    - static/images/passport/hot_tip.png
    - static/images/passport/login_bg.mp4
    - static/images/tabs/home.png
    - static/images/tabs/home_active.png
    - static/images/tabs/chat.png
    - static/images/tabs/chat_active.png
    - static/images/tabs/club_active.png
    - static/images/tabs/discover.png
    - static/images/tabs/discover_active.png
    - static/images/tabs/profile.png
    - static/images/tabs/profile_active.png
    - static/images/discover/taskhall/task_bg.jpg
    - static/images/discover/taskhall/task_item_bg.png
    - static/images/discover/taskhall/rectangle_yellow.png
    - static/images/discover/taskhall/task_picture.png
    - static/images/discover/taskhall/task_video.png
    - static/images/common/icon_back.png
    - static/images/common/icon_right.png
    - static/images/common/place_nodata.png
    - static/images/common/earth.png
